version: "3.8"
volumes:
  php-fpm-socket:
  db-store:
services:
  app:
    build:
      context: .
      dockerfile: ./docker/php/Dockerfile
    volumes:
      - php-fpm-socket:/var/run/php-fpm
      - .:/work/backend
    environment:
      - DB_CONNECTION=mysql
      - DB_HOST=db
      - DB_PORT=3306
      - DB_DATABASE=ask_form
      - DB_USERNAME=ask_user
      - DB_PASSWORD=password123

  web:
    build:
      context: .
      dockerfile: ./docker/nginx/Dockerfile
    ports:
      - ${WEB_PORT:-80}:80
    volumes:
      - php-fpm-socket:/var/run/php-fpm
      - .:/work/backend

  db:
    build:
      context: .
      dockerfile: ./docker/mysql/Dockerfile
    ports:
      - 3306:3306
    volumes:
      - db-store:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=ask_form
      - MYSQL_USER=ask_user
      - MYSQL_PASSWORD=password123
      - MYSQL_ROOT_PASSWORD=${DB_PASS:-secret}
