version: "3.8"
volumes:
  php-fpm-socket:
services:
  app:
    build:
      context: .
      dockerfile: ./docker/php/Dockerfile
    volumes:
      - php-fpm-socket:/var/run/php-fpm
      - .:/work/backend
    environment:
      - DB_CONNECTION=mysql
      - DB_HOST=ask-form-web.ctusuktdtoal.ap-northeast-1.rds.amazonaws.com
      - DB_PORT=3306
      - DB_DATABASE=ASK_FORMS
      - DB_USERNAME=ask_form
      - DB_PASSWORD=password

  web:
    build:
      context: .
      dockerfile: ./docker/nginx/Dockerfile
    ports:
      - ${WEB_PORT:-80}:80
    volumes:
      - php-fpm-socket:/var/run/php-fpm
      - .:/work/backend

